<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-SGPKRE7" failures="2" tests="7" name="TestCase_Priority.TestCases" time="70.816" errors="1" timestamp="2024-12-19T04:34:24 GMT-08:00" skipped="0">
  <testcase classname="TestCase_Priority.TestCases" name="subheading" time="4.805">
    <failure message="expected [Login to manage your text and categories] but found [Login to manage your tests and categories]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Login to manage your text and categories] but found [Login to manage your tests and categories]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestCase_Priority.TestCases.subheading(TestCases.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- subheading -->
  <testcase classname="TestCase_Priority.TestCases" name="Invalidcredential3" time="5.773"/>
  <testcase classname="TestCase_Priority.TestCases" name="Invalidcredential2" time="4.943"/>
  <testcase classname="TestCase_Priority.TestCases" name="validcredential" time="29.432"/>
  <testcase classname="TestCase_Priority.TestCases" name="Invalidcredential" time="6.304"/>
  <testcase classname="TestCase_Priority.TestCases" name="Invalidcredential4" time="6.939">
    <error message="invalid selector
from javascript error: {&quot;status&quot;:32,&quot;value&quot;:&quot;Unable to locate an element with the xpath expression @Test\r\nvoid Invalidcredential3()\r\n{\r\n\tWebDriver driver=new ChromeDriver();\r\n\tdriver.get(\&quot;https://javabykiran.com/selenium/login.html\&quot;);\r\n\tdriver.findElement(By.xpath(\&quot;//*[@id=\\\&quot;username\\\&quot;]\&quot;)).sendKeys(\&quot;adminrtp\&quot;);\r\n\tdriver.findElement(By.xpath(\&quot;//*[@id=\\\&quot;password\\\&quot;]\&quot;)).sendKeys(\&quot;password123\&quot;);\r\n\tdriver.findElement(By.xpath(\&quot;//*[@id=\\\&quot;login-form\\\&quot;]/button\&quot;)).click();\r\n\tString ActualErrorMessage=driver.findElement(By.xpath(\&quot;//*[@id=\\\&quot;error-message\\\&quot;]\&quot;)).getText();\r\n\tString ExpectedResult=\&quot;Invalid username or password\&quot;;\r\n\tAssert.assertEquals(ActualErrorMessage,ExpectedResult);\r\n\t\r\n}\r\n\r\n because of the following error:\nSyntaxError: Failed to execute &#039;evaluate&#039; on &#039;Document&#039;: The string &#039;@Test\r\nvoid Invalidcredential3()\r\n{\r\n\tWebDriver driver=new ChromeDriver();\r\n\tdriver.get(\&quot;https://javabykiran.com/selenium/login.html\&quot;);\r\n\tdriver.findElement(By.xpath(\&quot;//*[@id=\\\&quot;username\\\&quot;]\&quot;)).sendKeys(\&quot;adminrtp\&quot;);\r\n\tdriver.findElement(By.xpath(\&quot;//*[@id=\\\&quot;password\\\&quot;]\&quot;)).sendKeys(\&quot;password123\&quot;);\r\n\tdriver.findElement(By.xpath(\&quot;//*[@id=\\\&quot;login-form\\\&quot;]/button\&quot;)).click();\r\n\tString ActualErrorMessage=driver.findElement(By.xpath(\&quot;//*[@id=\\\&quot;error-message\\\&quot;]\&quot;)).getText();\r\n\tString ExpectedResult=\&quot;Invalid username or password\&quot;;\r\n\tAssert.assertEquals(ActualErrorMessage,ExpectedResult);\r\n\t\r\n}\r\n\r\n&#039; is not a valid XPath expression.&quot;}
  (Session info: chrome=131.0.6778.140)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Build info: version: &#039;4.27.0&#039;, revision: &#039;d6e718d134&#039;
System info: os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;22.0.2&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [6ab1d44bf3dd1f7e232ee15036b923dc, findElement {using=xpath, value=@Test
void Invalidcredential3()
{
	WebDriver driver=new ChromeDriver();
	driver.get(&quot;https://javabykiran.com/selenium/login.html&quot;);
	driver.findElement(By.xpath(&quot;//*[@id=\&quot;username\&quot;]&quot;)).sendKeys(&quot;adminrtp&quot;);
	driver.findElement(By.xpath(&quot;//*[@id=\&quot;password\&quot;]&quot;)).sendKeys(&quot;password123&quot;);
	driver.findElement(By.xpath(&quot;//*[@id=\&quot;login-form\&quot;]/button&quot;)).click();
	String ActualErrorMessage=driver.findElement(By.xpath(&quot;//*[@id=\&quot;error-message\&quot;]&quot;)).getText();
	String ExpectedResult=&quot;Invalid username or password&quot;;
	Assert.assertEquals(ActualErrorMessage,ExpectedResult);
	
}

}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.140, chrome: {chromedriverVersion: 131.0.6778.204 (52183f9e99a..., userDataDir: C:\Users\VMCS\AppData\Local...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:51636}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:51636/devtoo..., se:cdpVersion: 131.0.6778.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6ab1d44bf3dd1f7e232ee15036b923dc" type="org.openqa.selenium.InvalidSelectorException">
      <![CDATA[org.openqa.selenium.InvalidSelectorException: invalid selector
from javascript error: {"status":32,"value":"Unable to locate an element with the xpath expression @Test\r\nvoid Invalidcredential3()\r\n{\r\n\tWebDriver driver=new ChromeDriver();\r\n\tdriver.get(\"https://javabykiran.com/selenium/login.html\");\r\n\tdriver.findElement(By.xpath(\"//*[@id=\\\"username\\\"]\")).sendKeys(\"adminrtp\");\r\n\tdriver.findElement(By.xpath(\"//*[@id=\\\"password\\\"]\")).sendKeys(\"password123\");\r\n\tdriver.findElement(By.xpath(\"//*[@id=\\\"login-form\\\"]/button\")).click();\r\n\tString ActualErrorMessage=driver.findElement(By.xpath(\"//*[@id=\\\"error-message\\\"]\")).getText();\r\n\tString ExpectedResult=\"Invalid username or password\";\r\n\tAssert.assertEquals(ActualErrorMessage,ExpectedResult);\r\n\t\r\n}\r\n\r\n because of the following error:\nSyntaxError: Failed to execute 'evaluate' on 'Document': The string '@Test\r\nvoid Invalidcredential3()\r\n{\r\n\tWebDriver driver=new ChromeDriver();\r\n\tdriver.get(\"https://javabykiran.com/selenium/login.html\");\r\n\tdriver.findElement(By.xpath(\"//*[@id=\\\"username\\\"]\")).sendKeys(\"adminrtp\");\r\n\tdriver.findElement(By.xpath(\"//*[@id=\\\"password\\\"]\")).sendKeys(\"password123\");\r\n\tdriver.findElement(By.xpath(\"//*[@id=\\\"login-form\\\"]/button\")).click();\r\n\tString ActualErrorMessage=driver.findElement(By.xpath(\"//*[@id=\\\"error-message\\\"]\")).getText();\r\n\tString ExpectedResult=\"Invalid username or password\";\r\n\tAssert.assertEquals(ActualErrorMessage,ExpectedResult);\r\n\t\r\n}\r\n\r\n' is not a valid XPath expression."}
  (Session info: chrome=131.0.6778.140)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '22.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [6ab1d44bf3dd1f7e232ee15036b923dc, findElement {using=xpath, value=@Test
void Invalidcredential3()
{
WebDriver driver=new ChromeDriver();
driver.get("https://javabykiran.com/selenium/login.html");
driver.findElement(By.xpath("//*[@id=\"username\"]")).sendKeys("adminrtp");
driver.findElement(By.xpath("//*[@id=\"password\"]")).sendKeys("password123");
driver.findElement(By.xpath("//*[@id=\"login-form\"]/button")).click();
String ActualErrorMessage=driver.findElement(By.xpath("//*[@id=\"error-message\"]")).getText();
String ExpectedResult="Invalid username or password";
Assert.assertEquals(ActualErrorMessage,ExpectedResult);

}

}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 131.0.6778.140, chrome: {chromedriverVersion: 131.0.6778.204 (52183f9e99a..., userDataDir: C:\Users\VMCS\AppData\Local...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:51636}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:51636/devtoo..., se:cdpVersion: 131.0.6778.140, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 6ab1d44bf3dd1f7e232ee15036b923dc
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElement(ElementLocation.java:165)
at org.openqa.selenium.remote.ElementLocation.findElement(ElementLocation.java:59)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:368)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:362)
at TestCase_Priority.TestCases.Invalidcredential4(TestCases.java:97)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </error>
  </testcase> <!-- Invalidcredential4 -->
  <testcase classname="TestCase_Priority.TestCases" name="testheading" time="12.620">
    <failure message="expected [Welcome Again] but found [Welcome Back]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Welcome Again] but found [Welcome Back]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestCase_Priority.TestCases.testheading(TestCases.java:17)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testheading -->
</testsuite> <!-- TestCase_Priority.TestCases -->
